/**
 * Project: the services, compute and disk, backups, migrations, extensions, Postgres and
 * pooler settings, logs, and the TypeScript types of the schema.
 */
import { ago, bytes, num, pct, withConfirm } from './helpers.js';
import { Panel, Stat, Health, List, ListRow, FILL } from './kit.js';

export function Project({ host, sb, project, current, overview, onChanged }) {
  const { h, ui, notify, tokens } = host;
  const { useState, useEffect } = host.react;
  const [view, setView] = useState('services');
  const [data, setData] = useState({});
  const [busy, setBusy] = useState(null);
  const [logSql, setLogSql] = useState("select timestamp, event_message\nfrom postgres_logs\norder by timestamp desc\nlimit 50");
  const [logs, setLogs] = useState(null);
  const [types, setTypes] = useState(null);
  const get = (key, path, post) => { setData((d) => ({ ...d, [key]: undefined })); (post ? sb(path, { method: 'POST', body: JSON.stringify(post) }) : sb(path)).then((r) => setData((d) => ({ ...d, [key]: r }))).catch((e) => setData((d) => ({ ...d, [key]: { error: e.message } }))); };
  useEffect(() => { setData({}); get('addons', '/mgmt/addons'); get('disk', '/mgmt/disk'); get('util', '/mgmt/disk/util'); get('backups', '/backups'); get('migrations', '/migrations'); get('extensions', '/extensions'); get('pg', '/mgmt/postgres-config'); get('pooler', '/pooler-config'); get('postgrest', '/postgrest-config'); get('readonly', '/mgmt/project/readonly'); }, [project]);
  const meta = (text) => h('span', { className: 'mpanel__meta' }, text);
  const empty = (text) => h('p', { className: 'mlead', style: { margin: 0 } }, text);
  const o = overview.data;
  const ext = Array.isArray(data.extensions) ? data.extensions : [];
  const installed = ext.filter((e) => e.installed);
  const toggleExt = async (e) => { setBusy(e.name); try { const r = e.installed ? await sb(`/extensions/${encodeURIComponent(e.name)}`, { method: 'DELETE' }) : await sb('/extensions', { method: 'POST', body: JSON.stringify({ name: e.name }) }); if (r && r.message) throw new Error(r.message); notify(e.installed ? `${e.name} removed` : `${e.name} enabled`, 'moss'); get('extensions', '/extensions'); onChanged(); } catch (err) { notify(err.message, 'rosin'); } finally { setBusy(null); } };
  const restart = async () => { setBusy('restart'); try { const r = await withConfirm((extra) => sb(`/mgmt/project/restart-services?soft=1${extra ? `&${extra}` : ''}`, { method: 'POST', body: JSON.stringify({}) }), () => Promise.resolve(window.confirm('Restart every service? Connections drop for a few seconds.'))); if (r && r.message) throw new Error(r.message); if (r) notify('Restarting', 'moss'); onChanged(); } catch (e) { notify(e.message, 'rosin'); } finally { setBusy(null); } };
  const runLogs = async () => { setBusy('logs'); setLogs(null); try { const r = await sb('/logs', { method: 'POST', body: JSON.stringify({ sql: logSql }) }); setLogs(r && r.result ? r.result : r && r.error ? { error: r.error.message || JSON.stringify(r.error) } : Array.isArray(r) ? r : { error: (r && r.message) || 'No rows' }); } catch (e) { setLogs({ error: e.message }); } finally { setBusy(null); } };
  const genTypes = async () => { setBusy('types'); try { const r = await sb('/types/typescript?schemas=public'); setTypes(r && r.types ? r.types : typeof r === 'string' ? r : `// ${(r && r.message) || 'nothing came back'}`); } catch (e) { setTypes(`// ${e.message}`); } finally { setBusy(null); } };
  const kv = (obj) => h(ui.InfoGrid, { items: Object.entries(obj || {}).filter(([, v]) => v !== null && typeof v !== 'object').slice(0, 40).map(([k, v]) => ({ label: k.replace(/_/g, ' '), value: String(v) })) });
  const tabs = [['services', 'Services'], ['compute', 'Compute and disk'], ['backups', 'Backups'], ['migrations', 'Migrations'], ['extensions', `Extensions ${installed.length}`], ['settings', 'Settings'], ['logs', 'Logs'], ['types', 'Types']];
  const body = view === 'services' ? h('div', null,
      o ? List(host, o.services.map((s) => ListRow(host, { key: s.name, lead: h('span', { className: 'mind-dot', style: { background: s.healthy ? 'var(--sy-moss)' : 'var(--sy-rosin)' } }), label: s.name, sub: `${s.status || (s.healthy ? 'healthy' : 'down')}${s.version ? ` - ${s.version}` : ''}` }))) : h(ui.Skeleton, { count: 5, height: 18 }),
      h('div', { style: { display: 'flex', gap: 6, marginTop: 'var(--sy-s3)', flexWrap: 'wrap', alignItems: 'center' } }, h(ui.Button, { className: 'sy-btn--sm', disabled: !!busy, onClick: restart }, busy === 'restart' ? 'Restarting...' : 'Restart the services'), data.readonly === undefined ? null : data.readonly && data.readonly.enabled ? h(ui.Button, { className: 'sy-btn--sm', variant: 'primary', onClick: async () => { try { await sb('/mgmt/project/readonly/disable', { method: 'POST', body: '{}' }); notify('Read-only mode lifted for 15 minutes', 'moss'); } catch (e) { notify(e.message, 'rosin'); } } }, 'Lift read-only mode') : meta('database is read-write')))
    : view === 'compute' ? h('div', { className: 'sb-row2' },
      Panel(host, { title: 'Compute', action: meta(data.addons && data.addons.selected_addons ? `${data.addons.selected_addons.length} add-on${data.addons.selected_addons.length === 1 ? '' : 's'}` : '') }, data.addons === undefined ? h(ui.Skeleton, { count: 4, height: 16 }) : data.addons.error ? empty(data.addons.error) : h('div', null, (data.addons.selected_addons || []).length ? List(host, data.addons.selected_addons.map((a) => ListRow(host, { key: a.type, label: a.variant && a.variant.name ? a.variant.name : a.type, sub: `${a.type}${a.variant && a.variant.price ? ` - ${a.variant.price.description}` : ''}` }))) : empty('On the free compute; no paid add-on.'), h('p', { className: 'mpanel__meta', style: { margin: '8px 0 0' } }, `Available: ${(data.addons.available_addons || []).map((a) => a.name).join(', ')}. Change them in the dashboard; they change the bill.`))),
      Panel(host, { title: 'Disk', action: meta(data.util && data.util.metrics ? pct(data.util.metrics.fs_used_bytes, data.util.metrics.fs_size_bytes) + ' used' : '') }, data.util === undefined ? h(ui.Skeleton, { count: 3, height: 16 }) : data.util.error || !data.util.metrics ? empty(data.util.error || 'No disk metrics on this plan.') : h(ui.InfoGrid, { items: [{ label: 'Size', value: bytes(data.util.metrics.fs_size_bytes) }, { label: 'Used', value: bytes(data.util.metrics.fs_used_bytes) }, { label: 'Free', value: bytes(data.util.metrics.fs_avail_bytes) }, { label: 'Type', value: data.disk && data.disk.type ? data.disk.type : '-' }, { label: 'IOPS', value: data.disk && data.disk.iops ? data.disk.iops : '-' }, { label: 'Read at', value: data.util.timestamp ? ago(data.util.timestamp) : '-' }] })))
    : view === 'backups' ? (data.backups === undefined ? h(ui.Skeleton, { count: 4, height: 16 }) : data.backups.error ? empty(data.backups.error) : h('div', null, h(ui.InfoGrid, { items: [{ label: 'Region', value: data.backups.region }, { label: 'Point-in-time recovery', value: data.backups.pitr_enabled ? 'on' : 'off' }, { label: 'WAL archiving', value: data.backups.walg_enabled ? 'on' : 'off' }, { label: 'Daily backups', value: (data.backups.backups || []).length }] }), (data.backups.backups || []).length ? h('div', { style: { marginTop: 'var(--sy-s2)', maxHeight: 360, overflow: 'auto', paddingRight: 14, scrollbarGutter: 'stable' } }, List(host, data.backups.backups.slice().reverse().map((b, i) => ListRow(host, { key: i, lead: h('span', { className: 'mind-dot', style: { background: b.status === 'COMPLETED' ? 'var(--sy-moss)' : 'var(--sy-brass)', width: 7, height: 7 } }), label: b.inserted_at ? new Date(b.inserted_at).toLocaleString() : `backup ${i + 1}`, sub: `${b.status || ''}${b.is_physical_backup ? ' - physical' : ''}` })))) : h('p', { className: 'mlead', style: { margin: 'var(--sy-s2) 0 0' } }, 'No daily backup listed yet. On the free plan backups are not kept; a paid plan keeps seven days, and point-in-time recovery is an add-on.'), h('p', { className: 'mpanel__meta', style: { margin: '8px 0 0' } }, 'Restoring overwrites the database; do it from the dashboard, or with Restore-Backup after a confirmation.')))
    : view === 'migrations' ? (data.migrations === undefined ? h(ui.Skeleton, { count: 4, height: 16 }) : data.migrations.error ? empty(data.migrations.error) : Array.isArray(data.migrations) && data.migrations.length ? h('div', { style: { maxHeight: 520, overflow: 'auto', paddingRight: 14, scrollbarGutter: 'stable' } }, List(host, data.migrations.slice().reverse().map((m) => ListRow(host, { key: m.version, lead: h('span', { className: 'mind-dot', style: { background: 'var(--sy-moss)', width: 7, height: 7 } }), label: m.name || m.version, sub: `version ${m.version}` })))) : empty('No migration applied through the management API. Migrations pushed with the CLI show here.'))
    : view === 'extensions' ? (data.extensions === undefined ? h(ui.Skeleton, { count: 6, height: 16 }) : data.extensions.error ? empty(data.extensions.error) : h('div', null, h('div', { className: 'mpanel__meta', style: { marginBottom: 6 } }, 'Installed'), List(host, installed.map((e) => ListRow(host, { key: e.name, lead: h('span', { className: 'mind-dot', style: { background: 'var(--sy-moss)' } }), label: e.name, sub: `${e.version}${e.schema ? ` in ${e.schema}` : ''}${e.description ? ` - ${e.description}` : ''}`, meta: /^(plpgsql|pg_graphql|pg_stat_statements|pgcrypto|uuid-ossp|supabase_vault|pgjwt)$/.test(e.name) ? '' : h('button', { type: 'button', className: 'sy-btn sy-btn--sm', disabled: !!busy, onClick: () => toggleExt(e) }, busy === e.name ? '...' : 'Remove') }))), h('div', { className: 'mpanel__meta', style: { margin: '12px 0 6px' } }, `Available (${ext.length - installed.length})`), h('div', { style: { maxHeight: 360, overflow: 'auto', paddingRight: 14, scrollbarGutter: 'stable' } }, List(host, ext.filter((e) => !e.installed).map((e) => ListRow(host, { key: e.name, lead: h('span', { className: 'mind-dot', style: { background: 'var(--sy-text-3)', width: 7, height: 7 } }), label: e.name, sub: `${e.latest_available || ''}${e.description ? ` - ${e.description}` : ''}`, meta: h('button', { type: 'button', className: 'sy-btn sy-btn--sm', disabled: !!busy, onClick: () => toggleExt(e) }, busy === e.name ? '...' : 'Enable') }))))))
    : view === 'settings' ? h('div', { className: 'sb-row2' },
      Panel(host, { title: 'Postgres', action: meta('changing these may restart the database') }, data.pg === undefined ? h(ui.Skeleton, { count: 5, height: 14 }) : data.pg.error ? empty(data.pg.error) : Object.keys(data.pg || {}).length ? kv(data.pg) : empty('Every setting at its default.')),
      Panel(host, { title: 'Pooler and API' }, data.pooler === undefined ? h(ui.Skeleton, { count: 4, height: 14 }) : h('div', null, data.pooler && !data.pooler.error ? kv(Array.isArray(data.pooler) ? data.pooler[0] : data.pooler) : empty(data.pooler && data.pooler.error || 'No pooler config'), h('div', { className: 'mpanel__meta', style: { margin: '10px 0 4px' } }, 'PostgREST'), data.postgrest && !data.postgrest.error ? kv(data.postgrest) : null)))
    : view === 'logs' ? h('div', { style: { display: 'flex', flexDirection: 'column', gap: 8 } },
      h('p', { className: 'mlead', style: { margin: 0 } }, 'Logs are queried with SQL over the log tables: postgres_logs, edge_logs, auth_logs, function_logs, storage_logs, realtime_logs.'),
      h(ui.CodeEditor, { value: logSql, language: 'sql', height: 110, onChange: setLogSql }),
      h('div', { style: { display: 'flex', gap: 6, flexWrap: 'wrap', alignItems: 'center' } }, h(ui.Button, { className: 'sy-btn--sm', variant: 'primary', disabled: busy === 'logs', onClick: runLogs }, busy === 'logs' ? 'Reading...' : 'Read the logs'), ...[['postgres_logs', 'Postgres'], ['edge_logs', 'API'], ['auth_logs', 'Auth'], ['function_logs', 'Functions'], ['storage_logs', 'Storage']].map(([t, l]) => h(ui.Chip, { key: t, onClick: () => setLogSql(`select timestamp, event_message\nfrom ${t}\norder by timestamp desc\nlimit 50`) }, l))),
      logs === null ? null : logs.error ? h('p', { className: 'mlead', style: { margin: 0, color: 'var(--sy-rosin)' } }, logs.error) : !logs.length ? empty('No log line in that window.') : h('div', { style: { maxHeight: 420, overflow: 'auto', paddingRight: 14, scrollbarGutter: 'stable', border: `1px solid ${tokens('line')}`, borderRadius: 8 } }, h('table', { className: 'sb-table sb-table--rows' }, h('thead', null, h('tr', null, Object.keys(logs[0]).map((k) => h('th', { key: k }, k)))), h('tbody', null, logs.map((r, i) => h('tr', { key: i }, Object.keys(logs[0]).map((k) => h('td', { key: k, style: { fontFamily: 'var(--sy-font-mono)', fontSize: 'var(--sy-fs-xs)', whiteSpace: 'pre-wrap' } }, k === 'timestamp' && Number(r[k]) ? new Date(Number(r[k]) / 1000).toLocaleString() : typeof r[k] === 'object' ? JSON.stringify(r[k]) : String(r[k] ?? '')))))))))
    : h('div', { style: { display: 'flex', flexDirection: 'column', gap: 8 } },
      h('p', { className: 'mlead', style: { margin: 0 } }, 'TypeScript types for the public schema, the same the CLI generates. Copy them into your project, or run Get-Types with -OutFile.'),
      h('div', { style: { display: 'flex', gap: 6 } }, h(ui.Button, { className: 'sy-btn--sm', variant: 'primary', disabled: busy === 'types', onClick: genTypes }, busy === 'types' ? 'Generating...' : types ? 'Generate again' : 'Generate'), types ? h(ui.Button, { className: 'sy-btn--sm', onClick: () => navigator.clipboard.writeText(types).then(() => notify('Types copied', 'moss')).catch(() => {}) }, 'Copy') : null, types && host.writeNote ? h(ui.Button, { className: 'sy-btn--sm', onClick: async () => { if (await host.writeNote(`${project} database types`, '```ts\n' + types + '\n```')) notify('Saved as a note', 'moss'); } }, 'Save as note') : null),
      types ? h(ui.CodeEditor, { value: types, language: 'typescript', height: 'max(240px, calc(100vh - 560px))', readOnly: true }) : null);
  return h('div', { style: { display: 'flex', flexDirection: 'column', gap: 'var(--sy-s3)' } },
    h('div', { className: 'mstats mstats--head' },
      Stat(host, { label: 'Status', value: o && o.project ? o.project.status.replace(/_/g, ' ').toLowerCase() : '...', tone: o && o.project && o.project.status === 'ACTIVE_HEALTHY' ? 'moss' : 'brass', hint: o && o.project ? `${o.project.region} - created ${new Date(o.project.createdAt).toLocaleDateString()}` : undefined }),
      Stat(host, { label: 'Postgres', value: o && o.project ? o.project.postgresVersion : '...', tone: 'muted', hint: o && o.database ? `up since ${ago(o.database.started_at)}` : undefined }),
      Stat(host, { label: 'Disk', value: o && o.disk ? pct(o.disk.usedBytes, o.disk.sizeBytes) : '...', tone: o && o.disk && o.disk.usedBytes / o.disk.sizeBytes > 0.8 ? 'rosin' : 'muted', hint: o && o.disk ? `${bytes(o.disk.usedBytes)} of ${bytes(o.disk.sizeBytes)}` : undefined }),
      Stat(host, { label: 'Backups', value: o && o.backups ? o.backups.pitr ? 'PITR' : o.backups.count ? `${o.backups.count} daily` : 'none kept' : '...', tone: o && o.backups && (o.backups.pitr || o.backups.count) ? 'moss' : 'brass' })),
    Panel(host, { title: tabs.find(([k]) => k === view)[1], wide: true, action: h('div', { style: { display: 'flex', gap: 6, flexWrap: 'wrap' } }, tabs.map(([k, l]) => h(ui.Chip, { key: k, on: view === k, onClick: () => setView(k) }, l))) }, body));
}

export function ProjectAside({ host, current, overview }) {
  const { h, ui } = host;
  const o = overview.data;
  const ref = current ? current.projectRef : '';
  const link = (label, path) => h('a', { key: path, className: 'sy-btn sy-btn--sm', href: `https://supabase.com/dashboard/project/${ref}${path}`, target: '_blank', rel: 'noreferrer' }, label);
  return h('div', { style: { display: 'flex', flexDirection: 'column', gap: 'var(--sy-s3)' } },
    current ? Panel(host, { title: 'Details' }, h(ui.InfoGrid, { items: [{ label: 'Ref', value: current.projectRef }, { label: 'URL', value: current.url }, { label: 'Region', value: o && o.project ? o.project.region : '-' }, { label: 'Organization', value: o && o.project ? o.project.organizationId : '-' }, { label: 'Repository', value: current.repoPath || 'none' }] })) : null,
    ref ? Panel(host, { title: 'In the dashboard' }, h('div', { style: { display: 'flex', flexWrap: 'wrap', gap: 6 } }, link('Settings', '/settings/general'), link('Billing', '/settings/billing/subscription'), link('Compute', '/settings/compute-and-disk'), link('Backups', '/database/backups/scheduled'), link('API keys', '/settings/api-keys'), link('Logs', '/logs/explorer'), link('Reports', '/reports'))) : null,
    current && current.repoPath ? Panel(host, { title: 'Repository' }, h('p', { className: 'mlead', style: { margin: '0 0 var(--sy-s2)', wordBreak: 'break-all' } }, current.repoPath), host.openShell ? h(ui.Button, { variant: 'primary', className: 'sy-btn--sm', onClick: () => host.openShell({ repo: current.name, path: current.repoPath }, { launch: true, label: current.name }) }, 'Start working') : null) : null);
}
